/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/l5zOdw2dpAK
 */
import { CardContent, Card } from "@/components/ui/card"

export function Component() {
  return (
    <Card className="w-full max-w-[210mm] h-full p-8">
      <CardContent className="px-4 py-6 md:px-6 md:py-12 lg:py-16 xl:py-20">
        <div className="space-y-4 print:space-y-2 print:divide-y print:divide-gray-200">
          <div className="space-y-2 print:divide-y print:divide-gray-200">
            <h1 className="text-4xl font-extrabold tracking-tight print:font-bold">The Secret Garden</h1>
            <div className="grid grid-cols-1 gap-1 not-2xl:grid-cols-2">
              <div className="space-y-1">
                <p className="text-gray-500">Published on May 1, 1911</p>
                <p className="text-gray-500">Ages 8-12</p>
              </div>
              <div className="space-y-1">
                <p className="text-right text-gray-500">ISBN 9780064401883 (pbk)</p>
                <p className="text-right text-gray-500">ISBN 9780064401883 (pbk)</p>
              </div>
            </div>
          </div>
          <div className="space-y-2">
            <p>
              When orphaned Mary Lennox comes to live at her uncle's great house on the Yorkshire Moors, she finds it
              full of secrets. The mansion has nearly one hundred rooms, and her uncle keeps himself locked up. And at
              night, she hears the sound of crying down one of the long corridors.
            </p>
            <p>
              The gardens surrounding the large property are Mary's only escape. Then, Mary discovers a secret garden,
              surrounded by high walls and locked with a missing key. With the help of two unexpected companions, Mary
              discovers a way in—and becomes determined to bring the garden back to life.
            </p>
            <p>
              Frances Hodgson Burnett's beloved classic celebrates the healing power of nature, and the magic of
              friendship.
            </p>
          </div>
          <div className="space-y-8 print:space-y-10">
            <div className="space-y-8 print:space-y-10">
              <h2 className="text-3xl font-extrabold tracking-tight print:text-2xl print:font-bold">
                Chapter 1: There Is No One Left
              </h2>
              <div className="prose prose-gray max-w-none print:prose-inherit">
                <p>
                  When Mary Lennox was sent to Misselthwaite Manor to live with her uncle, everybody said she was the
                  most disagreeable-looking child ever seen. It was true, too. She had a little thin face and a little
                  thin body, thin light hair and a sour expression. She was as tyrannical and selfish a little pig as
                  ever lived.
                </p>
                <p>
                  The fact was that the fresh Yorkshire air was doing her good. She was beginning to look less thin, and
                  her color was better. She was beginning to look like a child who was nice to look at. And she was
                  nicer to look at than she had been because she was beginning to look like a child who was nice to look
                  at.
                </p>
              </div>
            </div>
            <div className="space-y-8 print:space-y-10">
              <h2 className="text-3xl font-extrabold tracking-tight print:text-2xl print:font-bold">
                Chapter 2: Mistress Mary Quite Contrary
              </h2>
              <div className="prose prose-gray max-w-none print:prose-inherit">
                <p>
                  Mary had liked to look at her mother from a distance and she had thought her very pretty, but as she
                  knew very little of her she could scarcely have been expected to love her or to miss her very much
                  when she was gone. She did not miss her at all, in fact, and as she was a self-absorbed child she gave
                  her entire thought to herself, as she had always done.
                </p>
                <p>
                  If she had been older she would no doubt have been very anxious at being left alone in the world, but
                  she was very young, and as she had always been taken care of, she supposed she always would be. What
                  she thought was that she would like to know if she was going to nice people, who would be polite to
                  her and give her her own way as her Ayah and the other native servants had done.
                </p>
              </div>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
